-- CREATE COLLAGE DATABASE
CREATE DATABASE Collage;

-- USING COLLAGE DATABASE
USE Collage;

-- CREATE STUDENT TABLE
CREATE TABLE Student(
SID INT PRIMARY KEY,
NAME VARCHAR(25),
BRANCH VARCHAR(25),
SEMESTER INT NOT NULL,
ADDRESS VARCHAR(100),
PHONE VARCHAR(20),
EMAIL VARCHAR(30)
);

INSERT INTO Student(SID,NAME,BRANCH,SEMESTER,ADDRESS,PHONE,EMAIL) 
VALUES
(401,'PUNEETH','CS',5,'SARASWATHIPURAM','9663217461','puneethkumarg96@gmail.com'),
(402,'RAMESH','CS',3,'SARASWATHIPURAM','9876543278','ramesh@gmail.com'),
(403,'DHANUSH','MECH',4,'VIJAYNAGARA','34567890567','dhanush@gmail.com'),
(404,'PRAJWAL','MECH',7,'JANATHANAGAR','9876543456','prajwal@gmail.com'),
(405,'VISHWAS','ELECTRICAL',2,'VIJAYNAGARA','1234567098','vishwas@gmail.com');

-- LIST ALL THE STUDENTS
SELECT * FROM Student;

-- INSERT INTO STUDENT TABLE 
INSERT INTO Student 
VALUES(406,'RAVI','EC',8,'KUVEMPUNAGARA','9876543210','ravi@gmail.com');

-- MODIFY THE ADDRESS OF THE STUDENT
UPDATE Student
SET ADDRESS = 'KUVEMPUNAGARA'
WHERE SID = 402;

-- DELETE STUDENT FROM THE TABLE
DELETE FROM Student
WHERE SID = 406;

-- LIST ALL THE STUDENTS FROM CS BRANCH
SELECT * FROM Student
WHERE BRANCH = 'CS';

-- LIST ALL THE STUDENTS FROM CS BRANCH AND RESIDE IN SARASWATHIPURAM
SELECT * FROM Student
WHERE BRANCH = 'CS' AND ADDRESS = 'SARASWATHIPURAM';